<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Cocoar.JsEval.Marten.Sandbox</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CS1591;CA1812;CA1852</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\JsEval.Linq\Cocoar.JsEval.Linq.csproj" />
  </ItemGroup>

</Project>
