<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\JsEval.Engine\Cocoar.JsEval.Engine.csproj" />
    <ProjectReference Include="..\..\JsEval.TsDefinition\Cocoar.JsEval.TsDefinition.csproj" />
    <ProjectReference Include="..\..\Modules\JsEval.Module.Common\Cocoar.JsEval.Module.Common.csproj" />
    <ProjectReference Include="..\..\Modules\JsEval.Module.Http\Cocoar.JsEval.Module.Http.csproj" />
    <ProjectReference Include="..\..\JsEval\Cocoar.JsEval.csproj" />
  </ItemGroup>

</Project>
